# Generated by Django 5.2.8 on 2026-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
